version: "3"
services:
  native:
    build: servers/
    hostname: native
    expose:
      - 9090/udp

  client:
    build: client/
    expose:
      - 2000/udp
    ports:
      - 2000:2000/udp
    depends_on:
      - native
