# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotodata.proto\"\x80\x01\n\x04\x44\x61ta\x12\x0e\n\x06string\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x03\x12\x18\n\x04\x64ict\x18\x03 \x01(\x0b\x32\n.Data.Dict\x12\x0b\n\x03int\x18\x04 \x01(\r\x12\r\n\x05\x66loat\x18\x05 \x01(\x01\x1a#\n\x04\x44ict\x12\x0c\n\x04Liya\x18\x01 \x01(\r\x12\r\n\x05Gosha\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protodata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=20
  _DATA._serialized_end=148
  _DATA_DICT._serialized_start=113
  _DATA_DICT._serialized_end=148
# @@protoc_insertion_point(module_scope)
